# Generated by Django 5.2 on 2025-05-26 02:59

import cpo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=50)),
                ('funcao', models.CharField(max_length=100)),
                ('competencia', models.CharField(max_length=20)),
                ('tabela', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('backoffice', 'Backoffice'), ('operacional', 'Operacional')], default='backoffice', max_length=20)),
                ('cpf', models.CharField(max_length=14, validators=[cpo.models.validar_cpf])),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('funcao', models.CharField(max_length=255)),
                ('PIS', models.CharField(blank=True, max_length=50, null=True)),
                ('data_admissao', models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('março', 'Março'), ('dezembro', 'Dezembro')], default='março', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='FolhaDePonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=20)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpo.colaborador')),
            ],
        ),
    ]
