# Generated by Django 5.2 on 2025-05-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='user',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(default='exemplo@dominio.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
    ]
