# Generated by Django 4.2.23 on 2025-06-11 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ctps',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CTPS'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FolhaDePonto',
        ),
    ]
