# Generated by Django 4.2.23 on 2025-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo', '0003_colaborador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
