# Generated by Django 4.2.23 on 2025-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo', '0004_alter_colaborador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ctps',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CTPS'),
        ),
    ]
