# Generated by Django 4.2.23 on 2025-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpo', '0005_colaborador_ctps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
    ]
